### ISSUE TITLE
Numpy and Pandas

### ISSUE THREAD

**Issue by Zoher15** [glciampaglia/knowledge_linker#14]
```
(env-kl) [zkachwal@h2 knowledge_linker]$ pip install .
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Processing /gpfs/home/z/k/zkachwal/Carbonate/knowledge_linker
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-QW1JDC/setup.py", line 20, in <module>
        from numpy import get_include
    ImportError: No module named numpy
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-QW1JDC/
```
Fixed by installing numpy.

After installing:
```
(env-kl) [zkachwal@h2 knowledge_linker]$ klinker -h
Traceback (most recent call last):
  File "/N/u/zkachwal/Carbonate/miniconda3/envs/env-kl/bin/klinker", line 6, in <module>
    from knowledge_linker.frontend.cmdline import main
  File "/N/u/zkachwal/Carbonate/miniconda3/envs/env-kl/lib/python2.7/site-packages/knowledge_linker/frontend/cmdline.py", line 20, in <module>
    from . import linkpred
  File "/N/u/zkachwal/Carbonate/miniconda3/envs/env-kl/lib/python2.7/site-packages/knowledge_linker/frontend/linkpred.py", line 22, in <module>
    import pandas as pd
ImportError: No module named pandas
```

**Comment by glciampaglia** [comment]
Should be fixed now in f02ad95, can you give it a try?
