### ISSUE TITLE
Incomplete package list in setup.py causes ImportError in klinker

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/knowledge_linker#3]
After installing the package

```
python setup.py install
```

Trying to run `klinker` will throw:

``` python-traceback
Traceback (most recent call last):
  File "/home/marvram/anaconda3/envs/p2/bin/klinker", line 11, in <module>
    load_entry_point('knowledge-linker==0.1rc0', 'console_scripts', 'klinker')()
  File "/home/marvram/anaconda3/envs/p2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/home/marvram/anaconda3/envs/p2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/home/marvram/anaconda3/envs/p2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2258, in load
  File "/home/marvram/anaconda3/envs/p2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "build/bdist.linux-x86_64/egg/knowledge_linker/__init__.py", line 31, in <module>
ImportError: cannot import name io
```

This is because setup.py only specifies `packages=['knowledge_linker']`, while it should do `packages=find_packages()`.

**Comment by glciampaglia** [comment]
Fixed in c33cadd146c2b6149703caa2da0b69e3a5891ec7
